export interface TemplateField {
  id: string;
  label: string;
  type: "text" | "textarea" | "date" | "number" | "select";
  placeholder: string;
  required: boolean;
  options?: { value: string; label: string }[];
}

export interface DocumentTemplate {
  id: string;
  name: string;
  shortName: string;
  description: string;
  icon: string;
  category: string;
  estimatedTime: string;
  fields: TemplateField[];
}

export const templates: DocumentTemplate[] = [
  {
    id: "nda",
    name: "Соглашение о неразглашении (NDA)",
    shortName: "NDA",
    description:
      "Защитите конфиденциальную информацию при работе с партнёрами, подрядчиками и сотрудниками.",
    icon: "shield",
    category: "Конфиденциальность",
    estimatedTime: "3 мин",
    fields: [
      {
        id: "disclosingParty",
        label: "Раскрывающая сторона (название организации / ФИО)",
        type: "text",
        placeholder: "ООО «Ваша компания»",
        required: true,
      },
      {
        id: "disclosingInn",
        label: "ИНН раскрывающей стороны",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "receivingParty",
        label: "Получающая сторона (название организации / ФИО)",
        type: "text",
        placeholder: "ИП Иванов И.И.",
        required: true,
      },
      {
        id: "receivingInn",
        label: "ИНН получающей стороны",
        type: "text",
        placeholder: "771234567890",
        required: true,
      },
      {
        id: "subject",
        label: "Предмет (какую информацию защищаем)",
        type: "textarea",
        placeholder:
          "Техническая документация, бизнес-планы, клиентская база...",
        required: true,
      },
      {
        id: "duration",
        label: "Срок действия",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "1", label: "1 год" },
          { value: "2", label: "2 года" },
          { value: "3", label: "3 года" },
          { value: "5", label: "5 лет" },
          { value: "indefinite", label: "Бессрочно" },
        ],
      },
      {
        id: "penalty",
        label: "Штраф за нарушение (₽)",
        type: "number",
        placeholder: "500000",
        required: true,
      },
      {
        id: "nonSolicitation",
        label: "Включить запрет на переманивание сотрудников",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "no", label: "Нет" },
          { value: "6months", label: "6 месяцев после расторжения" },
          { value: "1year", label: "1 год после расторжения" },
        ],
      },
      {
        id: "ipOwnership",
        label: "Принадлежность интеллектуальной собственности",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "disclosing", label: "Раскрывающей стороне" },
          { value: "receiving", label: "Получающей стороне" },
          { value: "joint", label: "Совместная собственность" },
        ],
      },
      {
        id: "materialsReturn",
        label: "Требование возврата всех материалов",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "no", label: "Нет" },
          { value: "yes", label: "Да, в течение 10 дней" },
          { value: "destruction", label: "Да, с уничтожением копий" },
        ],
      },
    ],
  },
  {
    id: "lease",
    name: "Договор аренды нежилого помещения",
    shortName: "Аренда",
    description:
      "Типовой договор аренды для офиса, склада или торгового помещения с защитой интересов арендатора.",
    icon: "building",
    category: "Недвижимость",
    estimatedTime: "4 мин",
    fields: [
      {
        id: "landlord",
        label: "Арендодатель (название / ФИО)",
        type: "text",
        placeholder: "ООО «Арендодатель»",
        required: true,
      },
      {
        id: "landlordInn",
        label: "ИНН арендодателя",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "tenant",
        label: "Арендатор (название / ФИО)",
        type: "text",
        placeholder: "ООО «Ваша компания»",
        required: true,
      },
      {
        id: "tenantInn",
        label: "ИНН арендатора",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "address",
        label: "Адрес помещения",
        type: "text",
        placeholder: "г. Москва, ул. Примерная, д. 1, оф. 101",
        required: true,
      },
      {
        id: "area",
        label: "Площадь (кв.м)",
        type: "number",
        placeholder: "50",
        required: true,
      },
      {
        id: "rent",
        label: "Арендная плата в месяц (₽)",
        type: "number",
        placeholder: "100000",
        required: true,
      },
      {
        id: "deposit",
        label: "Обеспечительный платёж (₽)",
        type: "number",
        placeholder: "100000",
        required: false,
      },
      {
        id: "utilities",
        label: "Оплата коммунальных услуг",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "landlord", label: "Включена в арендную плату" },
          { value: "tenant", label: "Оплачивает арендатор отдельно" },
          { value: "shared", label: "Делится поровну" },
        ],
      },
      {
        id: "repairs",
        label: "Ремонт и техническое обслуживание",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "landlord", label: "За счёт арендодателя" },
          { value: "tenant", label: "За счёт арендатора" },
          { value: "both", label: "В зависимости от типа ремонта" },
        ],
      },
      {
        id: "subrental",
        label: "Разрешить субаренду",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "no", label: "Не разрешить" },
          { value: "with_permission", label: "С согласия арендодателя" },
          { value: "allowed", label: "Разрешить" },
        ],
      },
      {
        id: "duration",
        label: "Срок аренды",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "11", label: "11 месяцев" },
          { value: "12", label: "1 год" },
          { value: "36", label: "3 года" },
          { value: "60", label: "5 лет" },
        ],
      },
      {
        id: "indexation",
        label: "Индексация арендной платы",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "no", label: "Без индексации" },
          { value: "cpi", label: "По индексу потребительских цен" },
          { value: "fixed", label: "Ежегодное увеличение на фиксированный %" },
        ],
      },
      {
        id: "startDate",
        label: "Дата начала",
        type: "date",
        placeholder: "",
        required: true,
      },
    ],
  },
  {
    id: "sale",
    name: "Договор купли-продажи",
    shortName: "Купля-продажа",
    description:
      "Договор для продажи товаров, оборудования или имущества между юридическими или физическими лицами.",
    icon: "handshake",
    category: "Торговля",
    estimatedTime: "4 мин",
    fields: [
      {
        id: "seller",
        label: "Продавец (название / ФИО)",
        type: "text",
        placeholder: "ООО «Продавец»",
        required: true,
      },
      {
        id: "sellerInn",
        label: "ИНН продавца",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "buyer",
        label: "Покупатель (название / ФИО)",
        type: "text",
        placeholder: "ООО «Покупатель»",
        required: true,
      },
      {
        id: "buyerInn",
        label: "ИНН покупателя",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "subject",
        label: "Предмет договора (что продаётся)",
        type: "textarea",
        placeholder: "Оборудование, товар, имущество...",
        required: true,
      },
      {
        id: "price",
        label: "Цена (₽)",
        type: "number",
        placeholder: "500000",
        required: true,
      },
      {
        id: "paymentTerms",
        label: "Условия оплаты",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "prepaid", label: "100% предоплата" },
          { value: "postpaid", label: "Оплата при получении" },
          { value: "partial", label: "50% предоплата, 50% при получении" },
          { value: "installments", label: "Рассрочка" },
        ],
      },
      {
        id: "riskTransfer",
        label: "Переход риска случайной гибели товара",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "delivery", label: "При передаче товара" },
          { value: "payment", label: "При полной оплате" },
          { value: "signing", label: "При подписании договора" },
        ],
      },
      {
        id: "packaging",
        label: "Упаковка и доставка",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "seller", label: "За счёт продавца" },
          { value: "buyer", label: "За счёт покупателя" },
          { value: "included", label: "Включены в цену" },
        ],
      },
      {
        id: "deliveryDate",
        label: "Срок поставки / передачи",
        type: "date",
        placeholder: "",
        required: true,
      },
      {
        id: "warranty",
        label: "Гарантийный срок",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "0", label: "Без гарантии" },
          { value: "6", label: "6 месяцев" },
          { value: "12", label: "1 год" },
          { value: "24", label: "2 года" },
        ],
      },
      {
        id: "claimsDeadline",
        label: "Срок для предъявления претензий к качеству",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "14", label: "14 дней с момента получения" },
          { value: "30", label: "30 дней с момента получения" },
          { value: "warranty", label: "В течение гарантийного срока" },
        ],
      },
    ],
  },
  {
    id: "service",
    name: "Договор оказания услуг",
    shortName: "Услуги",
    description:
      "Для оформления отношений с подрядчиками, фрилансерами и поставщиками услуг.",
    icon: "briefcase",
    category: "Услуги",
    estimatedTime: "4 мин",
    fields: [
      {
        id: "contractor",
        label: "Исполнитель (название / ФИО)",
        type: "text",
        placeholder: "ИП Петров П.П.",
        required: true,
      },
      {
        id: "contractorInn",
        label: "ИНН исполнителя",
        type: "text",
        placeholder: "771234567890",
        required: true,
      },
      {
        id: "client",
        label: "Заказчик (название / ФИО)",
        type: "text",
        placeholder: "ООО «Ваша компания»",
        required: true,
      },
      {
        id: "clientInn",
        label: "ИНН заказчика",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "services",
        label: "Описание услуг",
        type: "textarea",
        placeholder: "Разработка веб-сайта, маркетинговые услуги...",
        required: true,
      },
      {
        id: "price",
        label: "Стоимость услуг (₽)",
        type: "number",
        placeholder: "200000",
        required: true,
      },
      {
        id: "confidentiality",
        label: "Включить обязательство конфиденциальности",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "no", label: "Нет" },
          { value: "yes", label: "Да" },
        ],
      },
      {
        id: "ipOwnership",
        label: "Принадлежность созданного контента / результатов",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "client", label: "Заказчику" },
          { value: "contractor", label: "Исполнителю" },
          { value: "shared", label: "Совместная собственность" },
        ],
      },
      {
        id: "subcontractors",
        label: "Привлечение третьих лиц (субподрядчиков)",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "prohibited", label: "Запрещено" },
          { value: "with_permission", label: "С согласия заказчика" },
          { value: "allowed", label: "Разрешено" },
        ],
      },
      {
        id: "deadline",
        label: "Срок выполнения",
        type: "date",
        placeholder: "",
        required: true,
      },
      {
        id: "paymentTerms",
        label: "Условия оплаты",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "prepaid", label: "100% предоплата" },
          { value: "postpaid", label: "Оплата по факту" },
          { value: "partial", label: "50/50" },
          { value: "milestone", label: "Поэтапная оплата" },
        ],
      },
      {
        id: "forceQajoure",
        label: "Включить форс-мажорные обстоятельства",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "no", label: "Нет" },
          { value: "yes", label: "Да" },
        ],
      },
    ],
  },
  {
    id: "employment",
    name: "Трудовой договор",
    shortName: "Трудовой",
    description:
      "Типовой трудовой договор, соответствующий ТК РФ, для оформления сотрудников.",
    icon: "users",
    category: "Кадры",
    estimatedTime: "4 мин",
    fields: [
      {
        id: "employer",
        label: "Работодатель (название организации)",
        type: "text",
        placeholder: "ООО «Ваша компания»",
        required: true,
      },
      {
        id: "employerInn",
        label: "ИНН работодателя",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "employee",
        label: "ФИО работника",
        type: "text",
        placeholder: "Иванов Иван Иванович",
        required: true,
      },
      {
        id: "position",
        label: "Должность",
        type: "text",
        placeholder: "Менеджер по продажам",
        required: true,
      },
      {
        id: "salary",
        label: "Оклад (₽/мес, до вычета НДФЛ)",
        type: "number",
        placeholder: "80000",
        required: true,
      },
      {
        id: "startDate",
        label: "Дата начала работы",
        type: "date",
        placeholder: "",
        required: true,
      },
      {
        id: "probation",
        label: "Испытательный срок",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "0", label: "Без испытательного срока" },
          { value: "1", label: "1 месяц" },
          { value: "3", label: "3 месяца" },
          { value: "6", label: "6 месяцев (для руководителей)" },
        ],
      },
      {
        id: "schedule",
        label: "Режим работы",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "full", label: "Полный рабочий день (5/2)" },
          { value: "shift", label: "Сменный график" },
          { value: "remote", label: "Удалённая работа" },
          { value: "flexible", label: "Гибкий график" },
        ],
      },
    ],
  },
  {
    id: "supply",
    name: "Договор поставки",
    shortName: "Поставка",
    description:
      "Для регулярных поставок товаров между компаниями. Регулируется ст. 506-524 ГК РФ.",
    icon: "truck",
    category: "Торговля",
    estimatedTime: "3 мин",
    fields: [
      {
        id: "supplier",
        label: "Поставщик (название организации)",
        type: "text",
        placeholder: "ООО «Поставщик»",
        required: true,
      },
      {
        id: "supplierInn",
        label: "ИНН поставщика",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "buyer",
        label: "Покупатель (название организации)",
        type: "text",
        placeholder: "ООО «Покупатель»",
        required: true,
      },
      {
        id: "buyerInn",
        label: "ИНН покупателя",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "goods",
        label: "Наименование товаров",
        type: "textarea",
        placeholder: "Канцелярские товары, оборудование, материалы...",
        required: true,
      },
      {
        id: "totalAmount",
        label: "Общая сумма поставки (₽)",
        type: "number",
        placeholder: "1000000",
        required: true,
      },
      {
        id: "deliveryFrequency",
        label: "Периодичность поставок",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "weekly", label: "Еженедельно" },
          { value: "biweekly", label: "Каждые 2 недели" },
          { value: "monthly", label: "Ежемесячно" },
          { value: "quarterly", label: "Ежеквартально" },
          { value: "once", label: "Разовая поставка" },
        ],
      },
      {
        id: "duration",
        label: "Срок действия договора",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "6", label: "6 месяцев" },
          { value: "12", label: "1 год" },
          { value: "24", label: "2 года" },
        ],
      },
    ],
  },
  {
    id: "loan",
    name: "Договор займа",
    shortName: "Займ",
    description:
      "Для оформления денежных займов между юридическими или физическими лицами.",
    icon: "wallet",
    category: "Финансы",
    estimatedTime: "2 мин",
    fields: [
      {
        id: "lender",
        label: "Займодавец (кто даёт деньги)",
        type: "text",
        placeholder: "ООО «Компания» / ФИО",
        required: true,
      },
      {
        id: "lenderInn",
        label: "ИНН займодавца",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "borrower",
        label: "Заёмщик (кто берёт деньги)",
        type: "text",
        placeholder: "ИП Иванов И.И. / ФИО",
        required: true,
      },
      {
        id: "borrowerInn",
        label: "ИНН заёмщика",
        type: "text",
        placeholder: "771234567890",
        required: true,
      },
      {
        id: "amount",
        label: "Сумма займа (₽)",
        type: "number",
        placeholder: "500000",
        required: true,
      },
      {
        id: "interestRate",
        label: "Процентная ставка",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "0", label: "Беспроцентный" },
          { value: "5", label: "5% годовых" },
          { value: "10", label: "10% годовых" },
          { value: "15", label: "15% годовых" },
          { value: "key", label: "Ключевая ставка ЦБ РФ" },
        ],
      },
      {
        id: "returnDate",
        label: "Срок возврата",
        type: "date",
        placeholder: "",
        required: true,
      },
      {
        id: "returnMethod",
        label: "Порядок возврата",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "lumpsum", label: "Единовременно в конце срока" },
          { value: "monthly", label: "Ежемесячные платежи" },
          { value: "quarterly", label: "Ежеквартальные платежи" },
        ],
      },
    ],
  },
  {
    id: "agency",
    name: "Агентский договор",
    shortName: "Агентский",
    description:
      "Для привлечения агентов на продажи, поиск клиентов и посредничество. Ст. 1005-1011 ГК РФ.",
    icon: "handshake",
    category: "Услуги",
    estimatedTime: "3 мин",
    fields: [
      {
        id: "principal",
        label: "Принципал (заказчик)",
        type: "text",
        placeholder: "ООО «Ваша компания»",
        required: true,
      },
      {
        id: "principalInn",
        label: "ИНН принципала",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "agent",
        label: "Агент (исполнитель)",
        type: "text",
        placeholder: "ИП Агентов А.А.",
        required: true,
      },
      {
        id: "agentInn",
        label: "ИНН агента",
        type: "text",
        placeholder: "771234567890",
        required: true,
      },
      {
        id: "subject",
        label: "Предмет (какие действия совершает агент)",
        type: "textarea",
        placeholder: "Поиск клиентов, заключение договоров от имени принципала...",
        required: true,
      },
      {
        id: "commission",
        label: "Агентское вознаграждение (%)",
        type: "number",
        placeholder: "10",
        required: true,
      },
      {
        id: "actingAs",
        label: "Агент действует",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "principal_name", label: "От имени принципала (поручение)" },
          { value: "own_name", label: "От своего имени (комиссия)" },
        ],
      },
      {
        id: "duration",
        label: "Срок действия",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "6", label: "6 месяцев" },
          { value: "12", label: "1 год" },
          { value: "indefinite", label: "Бессрочно" },
        ],
      },
    ],
  },
  {
    id: "contractor",
    name: "Договор подряда",
    shortName: "Подряд",
    description:
      "Для выполнения конкретных работ с материальным результатом — ремонт, строительство, разработка.",
    icon: "hammer",
    category: "Услуги",
    estimatedTime: "4 мин",
    fields: [
      {
        id: "customer",
        label: "Заказчик (название / ФИО)",
        type: "text",
        placeholder: "ООО «Заказчик»",
        required: true,
      },
      {
        id: "customerInn",
        label: "ИНН заказчика",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "contractor",
        label: "Подрядчик (название / ФИО)",
        type: "text",
        placeholder: "ИП Мастеров М.М.",
        required: true,
      },
      {
        id: "contractorInn",
        label: "ИНН подрядчика",
        type: "text",
        placeholder: "771234567890",
        required: true,
      },
      {
        id: "work",
        label: "Описание работ",
        type: "textarea",
        placeholder: "Ремонт офиса, разработка ПО, строительство...",
        required: true,
      },
      {
        id: "price",
        label: "Стоимость работ (₽)",
        type: "number",
        placeholder: "300000",
        required: true,
      },
      {
        id: "materials",
        label: "Материалы предоставляет",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "contractor", label: "Подрядчик" },
          { value: "customer", label: "Заказчик" },
          { value: "both", label: "Частично каждая сторона" },
        ],
      },
      {
        id: "paymentSchedule",
        label: "График платежей",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "end", label: "100% в конце после приёмки" },
          { value: "start_end", label: "50% предоплата, 50% в конце" },
          { value: "stages", label: "По этапам выполнения работ" },
        ],
      },
      {
        id: "startDate",
        label: "Дата начала работ",
        type: "date",
        placeholder: "",
        required: true,
      },
      {
        id: "endDate",
        label: "Дата окончания работ",
        type: "date",
        placeholder: "",
        required: true,
      },
      {
        id: "warranty",
        label: "Гарантийный срок на результат",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "0", label: "Без гарантии" },
          { value: "6", label: "6 месяцев" },
          { value: "12", label: "1 год" },
          { value: "24", label: "2 года" },
          { value: "60", label: "5 лет" },
        ],
      },
      {
        id: "hiddenDefects",
        label: "Срок обнаружения скрытых недостатков",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "30", label: "30 дней" },
          { value: "60", label: "60 дней" },
          { value: "warranty_period", label: "В течение гарантийного срока" },
        ],
      },
    ],
  },
];

export function getTemplate(id: string): DocumentTemplate | undefined {
  return templates.find((t) => t.id === id);
}
