export interface TemplateField {
  id: string;
  label: string;
  type: "text" | "textarea" | "date" | "number" | "select";
  placeholder: string;
  required: boolean;
  options?: { value: string; label: string }[];
  group?: "parties" | "conditions" | "dates" | "payment" | "additional";
}

export interface DocumentTemplate {
  id: string;
  name: string;
  shortName: string;
  description: string;
  icon: string;
  category: string;
  estimatedTime: string;
  fields: TemplateField[];
}

export const templates: DocumentTemplate[] = [
  {
    id: "nda",
    name: "Соглашение о неразглашении (NDA)",
    shortName: "NDA",
    description:
      "Защитите конфиденциальную информацию при работе с партнёрами, подрядчиками и сотрудниками.",
    icon: "shield",
    category: "Конфиденциальность",
    estimatedTime: "3 мин",
    fields: [
      {
        id: "disclosingParty",
        label: "Раскрывающая сторона (название организации / ФИО)",
        type: "text",
        placeholder: "ООО «Ваша компания»",
        required: true,
        group: "parties",
      },
      {
        id: "disclosingInn",
        label: "ИНН раскрывающей стороны",
        type: "text",
        placeholder: "7712345678",
        required: true,
        group: "parties",
      },
      {
        id: "receivingParty",
        label: "Получающая сторона (название организации / ФИО)",
        type: "text",
        placeholder: "ИП Иванов И.И.",
        required: true,
        group: "parties",
      },
      {
        id: "receivingInn",
        label: "ИНН получающей стороны",
        type: "text",
        placeholder: "771234567890",
        required: true,
        group: "parties",
      },
      {
        id: "subject",
        label: "Предмет (какую информацию защищаем)",
        type: "textarea",
        placeholder:
          "Техническая документация, бизнес-планы, клиентская база...",
        required: true,
        group: "conditions",
      },
      {
        id: "duration",
        label: "Срок действия",
        type: "select",
        placeholder: "",
        required: true,
        group: "dates",
        options: [
          { value: "1", label: "1 год" },
          { value: "2", label: "2 года" },
          { value: "3", label: "3 года" },
          { value: "5", label: "5 лет" },
          { value: "indefinite", label: "Бессрочно" },
        ],
      },
      {
        id: "penalty",
        label: "Штраф за нарушение (₽)",
        type: "number",
        placeholder: "500000",
        required: true,
        group: "conditions",
      },
      {
        id: "nonSolicitation",
        label: "Включить запрет на переманивание сотрудников",
        type: "select",
        placeholder: "",
        required: false,
        group: "additional",
        options: [
          { value: "no", label: "Нет" },
          { value: "6months", label: "6 месяцев после расторжения" },
          { value: "1year", label: "1 год после расторжения" },
        ],
      },
      {
        id: "ipOwnership",
        label: "Принадлежность интеллектуальной собственности",
        type: "select",
        placeholder: "",
        required: false,
        group: "additional",
        options: [
          { value: "disclosing", label: "Раскрывающей стороне" },
          { value: "receiving", label: "Получающей стороне" },
          { value: "joint", label: "Совместная собственность" },
        ],
      },
      {
        id: "materialsReturn",
        label: "Требование возврата всех материалов",
        type: "select",
        placeholder: "",
        required: false,
        group: "additional",
        options: [
          { value: "no", label: "Нет" },
          { value: "yes", label: "Да, в течение 10 дней" },
          { value: "destruction", label: "Да, с уничтожением копий" },
        ],
      },
    ],
  },
  {
    id: "lease",
    name: "Договор аренды нежилого помещения",
    shortName: "Аренда",
    description:
      "Типовой договор аренды для офиса, склада или торгового помещения с защитой интересов арендатора.",
    icon: "building",
    category: "Недвижимость",
    estimatedTime: "4 мин",
    fields: [
      {
        id: "landlord",
        label: "Арендодатель (название / ФИО)",
        type: "text",
        placeholder: "ООО «Арендодатель»",
        required: true,
      },
      {
        id: "landlordInn",
        label: "ИНН арендодателя",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "tenant",
        label: "Арендатор (название / ФИО)",
        type: "text",
        placeholder: "ООО «Ваша компания»",
        required: true,
      },
      {
        id: "tenantInn",
        label: "ИНН арендатора",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "address",
        label: "Адрес помещения",
        type: "text",
        placeholder: "г. Москва, ул. Примерная, д. 1, оф. 101",
        required: true,
      },
      {
        id: "area",
        label: "Площадь (кв.м)",
        type: "number",
        placeholder: "50",
        required: true,
      },
      {
        id: "rent",
        label: "Арендная плата в месяц (₽)",
        type: "number",
        placeholder: "100000",
        required: true,
      },
      {
        id: "deposit",
        label: "Обеспечительный платёж (₽)",
        type: "number",
        placeholder: "100000",
        required: false,
      },
      {
        id: "utilities",
        label: "Оплата коммунальных услуг",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "landlord", label: "Включена в арендную плату" },
          { value: "tenant", label: "Оплачивает арендатор отдельно" },
          { value: "shared", label: "Делится поровну" },
        ],
      },
      {
        id: "repairs",
        label: "Ремонт и техническое обслуживание",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "landlord", label: "За счёт арендодателя" },
          { value: "tenant", label: "За счёт арендатора" },
          { value: "both", label: "В зависимости от типа ремонта" },
        ],
      },
      {
        id: "subrental",
        label: "Разрешить субаренду",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "no", label: "Не разрешить" },
          { value: "with_permission", label: "С согласия арендодателя" },
          { value: "allowed", label: "Разрешить" },
        ],
      },
      {
        id: "duration",
        label: "Срок аренды",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "11", label: "11 месяцев" },
          { value: "12", label: "1 год" },
          { value: "36", label: "3 года" },
          { value: "60", label: "5 лет" },
        ],
      },
      {
        id: "indexation",
        label: "Индексация арендной платы",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "no", label: "Без индексации" },
          { value: "cpi", label: "По индексу потребительских цен" },
          { value: "fixed", label: "Ежегодное увеличение на фиксированный %" },
        ],
      },
      {
        id: "startDate",
        label: "Дата начала",
        type: "date",
        placeholder: "",
        required: true,
      },
    ],
  },
  {
    id: "sale",
    name: "Договор купли-продажи",
    shortName: "Купля-продажа",
    description:
      "Договор для продажи товаров, оборудования или имущества между юридическими или физическими лицами.",
    icon: "handshake",
    category: "Торговля",
    estimatedTime: "4 мин",
    fields: [
      {
        id: "seller",
        label: "Продавец (название / ФИО)",
        type: "text",
        placeholder: "ООО «Продавец»",
        required: true,
      },
      {
        id: "sellerInn",
        label: "ИНН продавца",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "buyer",
        label: "Покупатель (название / ФИО)",
        type: "text",
        placeholder: "ООО «Покупатель»",
        required: true,
      },
      {
        id: "buyerInn",
        label: "ИНН покупателя",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "subject",
        label: "Предмет договора (что продаётся)",
        type: "textarea",
        placeholder: "Оборудование, товар, имущество...",
        required: true,
      },
      {
        id: "price",
        label: "Цена (₽)",
        type: "number",
        placeholder: "500000",
        required: true,
      },
      {
        id: "paymentTerms",
        label: "Условия оплаты",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "prepaid", label: "100% предоплата" },
          { value: "postpaid", label: "Оплата при получении" },
          { value: "partial", label: "50% предоплата, 50% при получении" },
          { value: "installments", label: "Рассрочка" },
        ],
      },
      {
        id: "riskTransfer",
        label: "Переход риска случайной гибели товара",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "delivery", label: "При передаче товара" },
          { value: "payment", label: "При полной оплате" },
          { value: "signing", label: "При подписании договора" },
        ],
      },
      {
        id: "packaging",
        label: "Упаковка и доставка",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "seller", label: "За счёт продавца" },
          { value: "buyer", label: "За счёт покупателя" },
          { value: "included", label: "Включены в цену" },
        ],
      },
      {
        id: "deliveryDate",
        label: "Срок поставки / передачи",
        type: "date",
        placeholder: "",
        required: true,
      },
      {
        id: "warranty",
        label: "Гарантийный срок",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "0", label: "Без гарантии" },
          { value: "6", label: "6 месяцев" },
          { value: "12", label: "1 год" },
          { value: "24", label: "2 года" },
        ],
      },
      {
        id: "claimsDeadline",
        label: "Срок для предъявления претензий к качеству",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "14", label: "14 дней с момента получения" },
          { value: "30", label: "30 дней с момента получения" },
          { value: "warranty", label: "В течение гарантийного срока" },
        ],
      },
    ],
  },
  {
    id: "service",
    name: "Договор оказания услуг",
    shortName: "Услуги",
    description:
      "Для оформления отношений с подрядчиками, фрилансерами и поставщиками услуг.",
    icon: "briefcase",
    category: "Услуги",
    estimatedTime: "4 мин",
    fields: [
      {
        id: "contractor",
        label: "Исполнитель (название / ФИО)",
        type: "text",
        placeholder: "ИП Петров П.П.",
        required: true,
      },
      {
        id: "contractorInn",
        label: "ИНН исполнителя",
        type: "text",
        placeholder: "771234567890",
        required: true,
      },
      {
        id: "client",
        label: "Заказчик (название / ФИО)",
        type: "text",
        placeholder: "ООО «Ваша компания»",
        required: true,
      },
      {
        id: "clientInn",
        label: "ИНН заказчика",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "services",
        label: "Описание услуг",
        type: "textarea",
        placeholder: "Разработка веб-сайта, маркетинговые услуги...",
        required: true,
      },
      {
        id: "price",
        label: "Стоимость услуг (₽)",
        type: "number",
        placeholder: "200000",
        required: true,
      },
      {
        id: "confidentiality",
        label: "Включить обязательство конфиденциальности",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "no", label: "Нет" },
          { value: "yes", label: "Да" },
        ],
      },
      {
        id: "ipOwnership",
        label: "Принадлежность созданного контента / результатов",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "client", label: "Заказчику" },
          { value: "contractor", label: "Исполнителю" },
          { value: "shared", label: "Совместная собственность" },
        ],
      },
      {
        id: "subcontractors",
        label: "Привлечение третьих лиц (субподрядчиков)",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "prohibited", label: "Запрещено" },
          { value: "with_permission", label: "С согласия заказчика" },
          { value: "allowed", label: "Разрешено" },
        ],
      },
      {
        id: "deadline",
        label: "Срок выполнения",
        type: "date",
        placeholder: "",
        required: true,
      },
      {
        id: "paymentTerms",
        label: "Условия оплаты",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "prepaid", label: "100% предоплата" },
          { value: "postpaid", label: "Оплата по факту" },
          { value: "partial", label: "50/50" },
          { value: "milestone", label: "Поэтапная оплата" },
        ],
      },
      {
        id: "forceQajoure",
        label: "Включить форс-мажорные обстоятельства",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "no", label: "Нет" },
          { value: "yes", label: "Да" },
        ],
      },
    ],
  },
  {
    id: "employment",
    name: "Трудовой договор",
    shortName: "Трудовой",
    description:
      "Типовой трудовой договор, соответствующий ТК РФ, для оформления сотрудников.",
    icon: "users",
    category: "Кадры",
    estimatedTime: "4 мин",
    fields: [
      {
        id: "employer",
        label: "Работодатель (название организации)",
        type: "text",
        placeholder: "ООО «Ваша компания»",
        required: true,
      },
      {
        id: "employerInn",
        label: "ИНН работодателя",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "employee",
        label: "ФИО работника",
        type: "text",
        placeholder: "Иванов Иван Иванович",
        required: true,
      },
      {
        id: "position",
        label: "Должность",
        type: "text",
        placeholder: "Менеджер по продажам",
        required: true,
      },
      {
        id: "salary",
        label: "Оклад (₽/мес, до вычета НДФЛ)",
        type: "number",
        placeholder: "80000",
        required: true,
      },
      {
        id: "startDate",
        label: "Дата начала работы",
        type: "date",
        placeholder: "",
        required: true,
      },
      {
        id: "probation",
        label: "Испытательный срок",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "0", label: "Без испытательного срока" },
          { value: "1", label: "1 месяц" },
          { value: "3", label: "3 месяца" },
          { value: "6", label: "6 месяцев (для руководителей)" },
        ],
      },
      {
        id: "schedule",
        label: "Режим работы",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "full", label: "Полный рабочий день (5/2)" },
          { value: "shift", label: "Сменный график" },
          { value: "remote", label: "Удалённая работа" },
          { value: "flexible", label: "Гибкий график" },
        ],
      },
    ],
  },
  {
    id: "supply",
    name: "Договор поставки",
    shortName: "Поставка",
    description:
      "Для регулярных поставок товаров между компаниями. Регулируется ст. 506-524 ГК РФ.",
    icon: "truck",
    category: "Торговля",
    estimatedTime: "3 мин",
    fields: [
      {
        id: "supplier",
        label: "Поставщик (название организации)",
        type: "text",
        placeholder: "ООО «Поставщик»",
        required: true,
      },
      {
        id: "supplierInn",
        label: "ИНН поставщика",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "buyer",
        label: "Покупатель (название организации)",
        type: "text",
        placeholder: "ООО «Покупатель»",
        required: true,
      },
      {
        id: "buyerInn",
        label: "ИНН покупателя",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "goods",
        label: "Наименование товаров",
        type: "textarea",
        placeholder: "Канцелярские товары, оборудование, материалы...",
        required: true,
      },
      {
        id: "totalAmount",
        label: "Общая сумма поставки (₽)",
        type: "number",
        placeholder: "1000000",
        required: true,
      },
      {
        id: "deliveryFrequency",
        label: "Периодичность поставок",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "weekly", label: "Еженедельно" },
          { value: "biweekly", label: "Каждые 2 недели" },
          { value: "monthly", label: "Ежемесячно" },
          { value: "quarterly", label: "Ежеквартально" },
          { value: "once", label: "Разовая поставка" },
        ],
      },
      {
        id: "duration",
        label: "Срок действия договора",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "6", label: "6 месяцев" },
          { value: "12", label: "1 год" },
          { value: "24", label: "2 года" },
        ],
      },
    ],
  },
  {
    id: "loan",
    name: "Договор займа",
    shortName: "Займ",
    description:
      "Для оформления денежных займов между юридическими или физическими лицами.",
    icon: "wallet",
    category: "Финансы",
    estimatedTime: "2 мин",
    fields: [
      {
        id: "lender",
        label: "Займодавец (кто даёт деньги)",
        type: "text",
        placeholder: "ООО «Компания» / ФИО",
        required: true,
      },
      {
        id: "lenderInn",
        label: "ИНН займодавца",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "borrower",
        label: "Заёмщик (кто берёт деньги)",
        type: "text",
        placeholder: "ИП Иванов И.И. / ФИО",
        required: true,
      },
      {
        id: "borrowerInn",
        label: "ИНН заёмщика",
        type: "text",
        placeholder: "771234567890",
        required: true,
      },
      {
        id: "amount",
        label: "Сумма займа (₽)",
        type: "number",
        placeholder: "500000",
        required: true,
      },
      {
        id: "interestRate",
        label: "Процентная ставка",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "0", label: "Беспроцентный" },
          { value: "5", label: "5% годовых" },
          { value: "10", label: "10% годовых" },
          { value: "15", label: "15% годовых" },
          { value: "key", label: "Ключевая ставка ЦБ РФ" },
        ],
      },
      {
        id: "returnDate",
        label: "Срок возврата",
        type: "date",
        placeholder: "",
        required: true,
      },
      {
        id: "returnMethod",
        label: "Порядок возврата",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "lumpsum", label: "Единовременно в конце срока" },
          { value: "monthly", label: "Ежемесячные платежи" },
          { value: "quarterly", label: "Ежеквартальные платежи" },
        ],
      },
    ],
  },
  {
    id: "agency",
    name: "Агентский договор",
    shortName: "Агентский",
    description:
      "Для привлечения агентов на продажи, поиск клиентов и посредничество. Ст. 1005-1011 ГК РФ.",
    icon: "handshake",
    category: "Услуги",
    estimatedTime: "3 мин",
    fields: [
      {
        id: "principal",
        label: "Принципал (заказчик)",
        type: "text",
        placeholder: "ООО «Ваша компания»",
        required: true,
      },
      {
        id: "principalInn",
        label: "ИНН принципала",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "agent",
        label: "Агент (исполнитель)",
        type: "text",
        placeholder: "ИП Агентов А.А.",
        required: true,
      },
      {
        id: "agentInn",
        label: "ИНН агента",
        type: "text",
        placeholder: "771234567890",
        required: true,
      },
      {
        id: "subject",
        label: "Предмет (какие действия совершает агент)",
        type: "textarea",
        placeholder: "Поиск клиентов, заключение договоров от имени принципала...",
        required: true,
      },
      {
        id: "commission",
        label: "Агентское вознаграждение (%)",
        type: "number",
        placeholder: "10",
        required: true,
      },
      {
        id: "actingAs",
        label: "Агент действует",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "principal_name", label: "От имени принципала (поручение)" },
          { value: "own_name", label: "От своего имени (комиссия)" },
        ],
      },
      {
        id: "duration",
        label: "Срок действия",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "6", label: "6 месяцев" },
          { value: "12", label: "1 год" },
          { value: "indefinite", label: "Бессрочно" },
        ],
      },
    ],
  },
  {
    id: "contractor",
    name: "Договор подряда",
    shortName: "Подряд",
    description:
      "Для выполнения конкретных работ с материальным результатом — ремонт, строительство, разработка.",
    icon: "hammer",
    category: "Услуги",
    estimatedTime: "4 мин",
    fields: [
      {
        id: "customer",
        label: "Заказчик (название / ФИО)",
        type: "text",
        placeholder: "ООО «Заказчик»",
        required: true,
      },
      {
        id: "customerInn",
        label: "ИНН заказчика",
        type: "text",
        placeholder: "7712345678",
        required: true,
      },
      {
        id: "contractor",
        label: "Подрядчик (название / ФИО)",
        type: "text",
        placeholder: "ИП Мастеров М.М.",
        required: true,
      },
      {
        id: "contractorInn",
        label: "ИНН подрядчика",
        type: "text",
        placeholder: "771234567890",
        required: true,
      },
      {
        id: "work",
        label: "Описание работ",
        type: "textarea",
        placeholder: "Ремонт офиса, разработка ПО, строительство...",
        required: true,
      },
      {
        id: "price",
        label: "Стоимость работ (₽)",
        type: "number",
        placeholder: "300000",
        required: true,
      },
      {
        id: "materials",
        label: "Материалы предоставляет",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "contractor", label: "Подрядчик" },
          { value: "customer", label: "Заказчик" },
          { value: "both", label: "Частично каждая сторона" },
        ],
      },
      {
        id: "paymentSchedule",
        label: "График платежей",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "end", label: "100% в конце после приёмки" },
          { value: "start_end", label: "50% предоплата, 50% в конце" },
          { value: "stages", label: "По этапам выполнения работ" },
        ],
      },
      {
        id: "startDate",
        label: "Дата начала работ",
        type: "date",
        placeholder: "",
        required: true,
      },
      {
        id: "endDate",
        label: "Дата окончания работ",
        type: "date",
        placeholder: "",
        required: true,
      },
      {
        id: "warranty",
        label: "Гарантийный срок на результат",
        type: "select",
        placeholder: "",
        required: true,
        options: [
          { value: "0", label: "Без гарантии" },
          { value: "6", label: "6 месяцев" },
          { value: "12", label: "1 год" },
          { value: "24", label: "2 года" },
          { value: "60", label: "5 лет" },
        ],
      },
      {
        id: "hiddenDefects",
        label: "Срок обнаружения скрытых недостатков",
        type: "select",
        placeholder: "",
        required: false,
        options: [
          { value: "30", label: "30 дней" },
          { value: "60", label: "60 дней" },
          { value: "warranty_period", label: "В течение гарантийного срока" },
        ],
      },
    ],
  },
  // ── Batch 1: short / supporting documents ──────────────────────
  {
    id: "amendment",
    name: "Дополнительное соглашение к договору",
    shortName: "Доп.соглашение",
    description:
      "Изменение условий действующего договора без перезаключения: реквизиты, цена, сроки, добавление/исключение пунктов.",
    icon: "file-plus",
    category: "Документооборот",
    estimatedTime: "2 мин",
    fields: [
      {
        id: "originalContractType",
        label: "Тип основного договора",
        type: "text",
        placeholder: "Договор оказания услуг",
        required: true,
        group: "parties",
      },
      {
        id: "originalContractNumber",
        label: "Номер основного договора",
        type: "text",
        placeholder: "12-А/2026",
        required: true,
        group: "parties",
      },
      {
        id: "originalContractDate",
        label: "Дата основного договора",
        type: "date",
        placeholder: "",
        required: true,
        group: "parties",
      },
      {
        id: "party1",
        label: "Первая сторона (название / ФИО)",
        type: "text",
        placeholder: "ООО «Заказчик»",
        required: true,
        group: "parties",
      },
      {
        id: "party1Inn",
        label: "ИНН первой стороны",
        type: "text",
        placeholder: "7712345678",
        required: true,
        group: "parties",
      },
      {
        id: "party1Role",
        label: "Роль первой стороны в договоре",
        type: "text",
        placeholder: "Заказчик",
        required: true,
        group: "parties",
      },
      {
        id: "party2",
        label: "Вторая сторона (название / ФИО)",
        type: "text",
        placeholder: "ИП Иванов И.И.",
        required: true,
        group: "parties",
      },
      {
        id: "party2Inn",
        label: "ИНН второй стороны",
        type: "text",
        placeholder: "771234567890",
        required: true,
        group: "parties",
      },
      {
        id: "party2Role",
        label: "Роль второй стороны в договоре",
        type: "text",
        placeholder: "Исполнитель",
        required: true,
        group: "parties",
      },
      {
        id: "changes",
        label: "Изменения по пунктам",
        type: "textarea",
        placeholder:
          "1. Изложить п. 2.1 Договора в следующей редакции: «Стоимость услуг составляет 150 000 (сто пятьдесят тысяч) рублей в месяц...».\n2. Дополнить раздел 4 Договора пунктом 4.5: «...».",
        required: true,
        group: "conditions",
      },
      {
        id: "effectiveDate",
        label: "Дата вступления изменений в силу",
        type: "date",
        placeholder: "",
        required: true,
        group: "dates",
      },
    ],
  },
  {
    id: "act-work",
    name: "Акт приёмки выполненных работ",
    shortName: "Акт работ",
    description:
      "Закрывающий документ к договору подряда: подтверждает приёмку результата работ Заказчиком и фиксирует сумму к оплате.",
    icon: "clipboard-check",
    category: "Документооборот",
    estimatedTime: "2 мин",
    fields: [
      {
        id: "contractNumber",
        label: "Номер договора подряда",
        type: "text",
        placeholder: "5-П/2026",
        required: true,
        group: "parties",
      },
      {
        id: "contractDate",
        label: "Дата договора подряда",
        type: "date",
        placeholder: "",
        required: true,
        group: "parties",
      },
      {
        id: "customer",
        label: "Заказчик (название / ФИО)",
        type: "text",
        placeholder: "ООО «Заказчик»",
        required: true,
        group: "parties",
      },
      {
        id: "customerInn",
        label: "ИНН заказчика",
        type: "text",
        placeholder: "7712345678",
        required: true,
        group: "parties",
      },
      {
        id: "contractor",
        label: "Подрядчик (название / ФИО)",
        type: "text",
        placeholder: "ООО «Подрядчик»",
        required: true,
        group: "parties",
      },
      {
        id: "contractorInn",
        label: "ИНН подрядчика",
        type: "text",
        placeholder: "7712345678",
        required: true,
        group: "parties",
      },
      {
        id: "workDescription",
        label: "Описание выполненных работ",
        type: "textarea",
        placeholder:
          "Капитальный ремонт офисного помещения площадью 120 кв.м по адресу: г. Москва, ул. Примерная, д. 1, оф. 5.",
        required: true,
        group: "conditions",
      },
      {
        id: "totalAmount",
        label: "Стоимость работ (₽)",
        type: "number",
        placeholder: "500000",
        required: true,
        group: "payment",
      },
      {
        id: "withVat",
        label: "НДС включён",
        type: "select",
        placeholder: "",
        required: false,
        group: "payment",
        options: [
          { value: "no", label: "Без НДС (УСН)" },
          { value: "20", label: "Включая НДС 20%" },
          { value: "10", label: "Включая НДС 10%" },
        ],
      },
      {
        id: "qualityNote",
        label: "Замечания по качеству",
        type: "select",
        placeholder: "",
        required: true,
        group: "additional",
        options: [
          { value: "none", label: "Замечаний нет, работы приняты в полном объёме" },
          { value: "minor", label: "Замечания устранены подрядчиком до подписания акта" },
          { value: "deferred", label: "Замечания отражены отдельным перечнем (Приложение)" },
        ],
      },
    ],
  },
  {
    id: "act-service",
    name: "Акт об оказании услуг",
    shortName: "Акт услуг",
    description:
      "Закрывающий документ к договору оказания услуг: фиксирует факт оказания услуг и сумму к оплате.",
    icon: "file-check",
    category: "Документооборот",
    estimatedTime: "2 мин",
    fields: [
      {
        id: "contractNumber",
        label: "Номер договора услуг",
        type: "text",
        placeholder: "8-У/2026",
        required: true,
        group: "parties",
      },
      {
        id: "contractDate",
        label: "Дата договора услуг",
        type: "date",
        placeholder: "",
        required: true,
        group: "parties",
      },
      {
        id: "customer",
        label: "Заказчик (название / ФИО)",
        type: "text",
        placeholder: "ООО «Заказчик»",
        required: true,
        group: "parties",
      },
      {
        id: "customerInn",
        label: "ИНН заказчика",
        type: "text",
        placeholder: "7712345678",
        required: true,
        group: "parties",
      },
      {
        id: "executor",
        label: "Исполнитель (название / ФИО)",
        type: "text",
        placeholder: "ИП Иванов И.И.",
        required: true,
        group: "parties",
      },
      {
        id: "executorInn",
        label: "ИНН исполнителя",
        type: "text",
        placeholder: "771234567890",
        required: true,
        group: "parties",
      },
      {
        id: "serviceDescription",
        label: "Описание оказанных услуг",
        type: "textarea",
        placeholder:
          "Юридическая консультация по договорному праву, подготовка проекта договора поставки, правовая экспертиза трёх контрагентов.",
        required: true,
        group: "conditions",
      },
      {
        id: "periodFrom",
        label: "Период оказания услуг — с",
        type: "date",
        placeholder: "",
        required: true,
        group: "dates",
      },
      {
        id: "periodTo",
        label: "Период оказания услуг — по",
        type: "date",
        placeholder: "",
        required: true,
        group: "dates",
      },
      {
        id: "totalAmount",
        label: "Стоимость услуг (₽)",
        type: "number",
        placeholder: "120000",
        required: true,
        group: "payment",
      },
      {
        id: "withVat",
        label: "НДС включён",
        type: "select",
        placeholder: "",
        required: false,
        group: "payment",
        options: [
          { value: "no", label: "Без НДС (УСН)" },
          { value: "20", label: "Включая НДС 20%" },
          { value: "10", label: "Включая НДС 10%" },
        ],
      },
    ],
  },
  {
    id: "receipt",
    name: "Расписка о получении денежных средств",
    shortName: "Расписка",
    description:
      "Письменное подтверждение получения денег. Используется при займе между физлицами или досрочном погашении.",
    icon: "receipt",
    category: "Финансы",
    estimatedTime: "1 мин",
    fields: [
      {
        id: "receiverFio",
        label: "ФИО получателя денег (полностью)",
        type: "text",
        placeholder: "Иванов Иван Иванович",
        required: true,
        group: "parties",
      },
      {
        id: "receiverPassport",
        label: "Паспорт получателя (серия и номер)",
        type: "text",
        placeholder: "4500 123456",
        required: true,
        group: "parties",
      },
      {
        id: "receiverPassportInfo",
        label: "Кем и когда выдан паспорт получателя",
        type: "text",
        placeholder: "ОВД района Тверской, выдан 12.05.2010",
        required: true,
        group: "parties",
      },
      {
        id: "receiverAddress",
        label: "Адрес регистрации получателя",
        type: "text",
        placeholder: "г. Москва, ул. Примерная, д. 1, кв. 1",
        required: true,
        group: "parties",
      },
      {
        id: "giverFio",
        label: "ФИО передавшего деньги (полностью)",
        type: "text",
        placeholder: "Петров Пётр Петрович",
        required: true,
        group: "parties",
      },
      {
        id: "giverPassport",
        label: "Паспорт передавшего (серия и номер)",
        type: "text",
        placeholder: "4500 654321",
        required: true,
        group: "parties",
      },
      {
        id: "amount",
        label: "Сумма (₽)",
        type: "number",
        placeholder: "100000",
        required: true,
        group: "payment",
      },
      {
        id: "purpose",
        label: "Основание / цель передачи",
        type: "textarea",
        placeholder:
          "В качестве займа сроком на 6 (шесть) месяцев под 5% (пять процентов) годовых",
        required: true,
        group: "conditions",
      },
      {
        id: "city",
        label: "Город составления",
        type: "text",
        placeholder: "Москва",
        required: true,
        group: "additional",
      },
    ],
  },
  // ── Batch 2: full contract templates ──────────────────────────
  {
    id: "gift",
    name: "Договор дарения",
    shortName: "Дарение",
    description:
      "Безвозмездная передача имущества от дарителя к одаряемому: денежных средств, движимого имущества, доли в уставном капитале.",
    icon: "gift",
    category: "Финансы",
    estimatedTime: "3 мин",
    fields: [
      {
        id: "donor",
        label: "Даритель (название / ФИО)",
        type: "text",
        placeholder: "Иванов Иван Иванович",
        required: true,
        group: "parties",
      },
      {
        id: "donorInn",
        label: "ИНН дарителя",
        type: "text",
        placeholder: "771234567890",
        required: true,
        group: "parties",
      },
      {
        id: "donee",
        label: "Одаряемый (название / ФИО)",
        type: "text",
        placeholder: "Петров Пётр Петрович",
        required: true,
        group: "parties",
      },
      {
        id: "doneeInn",
        label: "ИНН одаряемого",
        type: "text",
        placeholder: "771234567891",
        required: true,
        group: "parties",
      },
      {
        id: "giftKind",
        label: "Что дарится",
        type: "select",
        placeholder: "",
        required: true,
        group: "conditions",
        options: [
          { value: "money", label: "Денежные средства" },
          { value: "movable", label: "Движимое имущество" },
          { value: "share", label: "Доля в уставном капитале ООО" },
        ],
      },
      {
        id: "giftDescription",
        label: "Подробное описание подарка",
        type: "textarea",
        placeholder:
          "Автомобиль марки Toyota Camry, 2020 года выпуска, VIN XW7BFFFF000123456, государственный регистрационный знак А123АА777",
        required: true,
        group: "conditions",
      },
      {
        id: "giftValue",
        label: "Стоимость подарка (₽)",
        type: "number",
        placeholder: "500000",
        required: true,
        group: "payment",
      },
      {
        id: "transferDate",
        label: "Дата передачи",
        type: "date",
        placeholder: "",
        required: true,
        group: "dates",
      },
      {
        id: "revocation",
        label: "Условие отмены дарения",
        type: "select",
        placeholder: "",
        required: false,
        group: "additional",
        options: [
          { value: "default", label: "По общим основаниям ст. 578 ГК РФ" },
          { value: "outlive", label: "При жизни дарителя — на случай переживания" },
        ],
      },
    ],
  },
  {
    id: "barter",
    name: "Договор мены",
    shortName: "Мена",
    description:
      "Обмен товарами между сторонами без денежных расчётов или с доплатой разницы стоимости.",
    icon: "arrow-left-right",
    category: "Торговля",
    estimatedTime: "3 мин",
    fields: [
      {
        id: "party1",
        label: "Первая сторона (название / ФИО)",
        type: "text",
        placeholder: "ООО «Сторона А»",
        required: true,
        group: "parties",
      },
      {
        id: "party1Inn",
        label: "ИНН первой стороны",
        type: "text",
        placeholder: "7712345678",
        required: true,
        group: "parties",
      },
      {
        id: "party2",
        label: "Вторая сторона (название / ФИО)",
        type: "text",
        placeholder: "ООО «Сторона Б»",
        required: true,
        group: "parties",
      },
      {
        id: "party2Inn",
        label: "ИНН второй стороны",
        type: "text",
        placeholder: "7712345679",
        required: true,
        group: "parties",
      },
      {
        id: "goods1",
        label: "Что передаёт первая сторона",
        type: "textarea",
        placeholder: "Партия офисной мебели: 10 столов и 20 стульев",
        required: true,
        group: "conditions",
      },
      {
        id: "value1",
        label: "Стоимость товара первой стороны (₽)",
        type: "number",
        placeholder: "200000",
        required: true,
        group: "payment",
      },
      {
        id: "goods2",
        label: "Что передаёт вторая сторона",
        type: "textarea",
        placeholder: "Принтер Xerox VersaLink C405DN, 1 шт.",
        required: true,
        group: "conditions",
      },
      {
        id: "value2",
        label: "Стоимость товара второй стороны (₽)",
        type: "number",
        placeholder: "200000",
        required: true,
        group: "payment",
      },
      {
        id: "exchangeDate",
        label: "Дата обмена",
        type: "date",
        placeholder: "",
        required: true,
        group: "dates",
      },
      {
        id: "differencePayment",
        label: "Если стоимости различаются — кто доплачивает",
        type: "select",
        placeholder: "",
        required: false,
        group: "payment",
        options: [
          { value: "none", label: "Стоимости равны, доплата не требуется" },
          { value: "p1pays", label: "Первая сторона доплачивает разницу" },
          { value: "p2pays", label: "Вторая сторона доплачивает разницу" },
        ],
      },
    ],
  },
  {
    id: "assignment",
    name: "Договор уступки прав требования (цессия)",
    shortName: "Цессия",
    description:
      "Передача права требования долга от первоначального кредитора (цедента) новому кредитору (цессионарию).",
    icon: "file-signature",
    category: "Финансы",
    estimatedTime: "3 мин",
    fields: [
      {
        id: "cedent",
        label: "Цедент (название / ФИО)",
        type: "text",
        placeholder: "ООО «Цедент»",
        required: true,
        group: "parties",
      },
      {
        id: "cedentInn",
        label: "ИНН цедента",
        type: "text",
        placeholder: "7712345678",
        required: true,
        group: "parties",
      },
      {
        id: "cessionary",
        label: "Цессионарий (название / ФИО)",
        type: "text",
        placeholder: "ООО «Цессионарий»",
        required: true,
        group: "parties",
      },
      {
        id: "cessionaryInn",
        label: "ИНН цессионария",
        type: "text",
        placeholder: "7712345679",
        required: true,
        group: "parties",
      },
      {
        id: "debtor",
        label: "Должник (название / ФИО)",
        type: "text",
        placeholder: "ООО «Должник»",
        required: true,
        group: "parties",
      },
      {
        id: "debtorInn",
        label: "ИНН должника",
        type: "text",
        placeholder: "7712345680",
        required: true,
        group: "parties",
      },
      {
        id: "originalContract",
        label: "Основание возникновения долга (договор и его дата)",
        type: "text",
        placeholder: "Договор поставки № 5-П от 12 марта 2025 г.",
        required: true,
        group: "conditions",
      },
      {
        id: "debtAmount",
        label: "Сумма уступаемого требования (₽)",
        type: "number",
        placeholder: "1000000",
        required: true,
        group: "payment",
      },
      {
        id: "cessionPrice",
        label: "Цена уступки (сколько цессионарий платит цеденту, ₽)",
        type: "number",
        placeholder: "850000",
        required: true,
        group: "payment",
      },
      {
        id: "noticeDeadline",
        label: "Срок уведомления должника",
        type: "select",
        placeholder: "",
        required: true,
        group: "dates",
        options: [
          { value: "5", label: "5 рабочих дней с подписания" },
          { value: "10", label: "10 рабочих дней с подписания" },
          { value: "30", label: "30 календарных дней с подписания" },
        ],
      },
    ],
  },
  {
    id: "franchise",
    name: "Договор коммерческой концессии (франчайзинг)",
    shortName: "Франчайзинг",
    description:
      "Использование комплекса исключительных прав правообладателя (товарный знак, ноу-хау) пользователем за вознаграждение.",
    icon: "store",
    category: "Услуги",
    estimatedTime: "4 мин",
    fields: [
      {
        id: "franchisor",
        label: "Правообладатель (название)",
        type: "text",
        placeholder: "ООО «Бренд»",
        required: true,
        group: "parties",
      },
      {
        id: "franchisorInn",
        label: "ИНН правообладателя",
        type: "text",
        placeholder: "7712345678",
        required: true,
        group: "parties",
      },
      {
        id: "franchisee",
        label: "Пользователь (название)",
        type: "text",
        placeholder: "ИП Иванов И.И.",
        required: true,
        group: "parties",
      },
      {
        id: "franchiseeInn",
        label: "ИНН пользователя",
        type: "text",
        placeholder: "771234567890",
        required: true,
        group: "parties",
      },
      {
        id: "trademark",
        label: "Товарный знак (наименование, № регистрации)",
        type: "text",
        placeholder: "«Бренд», свидетельство Роспатента № 123456",
        required: true,
        group: "conditions",
      },
      {
        id: "territory",
        label: "Территория действия",
        type: "text",
        placeholder: "г. Москва и Московская область",
        required: true,
        group: "conditions",
      },
      {
        id: "exclusivity",
        label: "Исключительность",
        type: "select",
        placeholder: "",
        required: true,
        group: "conditions",
        options: [
          { value: "exclusive", label: "Исключительная (один пользователь на территории)" },
          { value: "non-exclusive", label: "Неисключительная" },
        ],
      },
      {
        id: "lumpSum",
        label: "Паушальный взнос (разовый, ₽)",
        type: "number",
        placeholder: "500000",
        required: true,
        group: "payment",
      },
      {
        id: "royaltyPercent",
        label: "Роялти (% от выручки)",
        type: "number",
        placeholder: "5",
        required: true,
        group: "payment",
      },
      {
        id: "term",
        label: "Срок действия",
        type: "select",
        placeholder: "",
        required: true,
        group: "dates",
        options: [
          { value: "3", label: "3 года" },
          { value: "5", label: "5 лет" },
          { value: "10", label: "10 лет" },
          { value: "indefinite", label: "Бессрочно" },
        ],
      },
    ],
  },
  {
    id: "transport",
    name: "Договор перевозки груза",
    shortName: "Перевозка",
    description:
      "Обязательство перевозчика доставить груз от пункта отправления в пункт назначения и выдать его получателю.",
    icon: "package",
    category: "Услуги",
    estimatedTime: "3 мин",
    fields: [
      {
        id: "carrier",
        label: "Перевозчик (название)",
        type: "text",
        placeholder: "ООО «Логистика»",
        required: true,
        group: "parties",
      },
      {
        id: "carrierInn",
        label: "ИНН перевозчика",
        type: "text",
        placeholder: "7712345678",
        required: true,
        group: "parties",
      },
      {
        id: "shipper",
        label: "Отправитель (название)",
        type: "text",
        placeholder: "ООО «Отправитель»",
        required: true,
        group: "parties",
      },
      {
        id: "shipperInn",
        label: "ИНН отправителя",
        type: "text",
        placeholder: "7712345679",
        required: true,
        group: "parties",
      },
      {
        id: "consignee",
        label: "Грузополучатель (название и адрес)",
        type: "text",
        placeholder: "ООО «Получатель», г. Санкт-Петербург, ул. Невский, д. 100",
        required: true,
        group: "parties",
      },
      {
        id: "cargo",
        label: "Описание груза",
        type: "textarea",
        placeholder:
          "Электробытовая техника в фабричной упаковке: 50 коробок, общим весом 1200 кг, объём 8 м³",
        required: true,
        group: "conditions",
      },
      {
        id: "originAddress",
        label: "Адрес погрузки",
        type: "text",
        placeholder: "г. Москва, ул. Складская, д. 5",
        required: true,
        group: "conditions",
      },
      {
        id: "destinationAddress",
        label: "Адрес выгрузки",
        type: "text",
        placeholder: "г. Санкт-Петербург, ул. Невский, д. 100",
        required: true,
        group: "conditions",
      },
      {
        id: "freightCharge",
        label: "Стоимость перевозки (₽)",
        type: "number",
        placeholder: "75000",
        required: true,
        group: "payment",
      },
      {
        id: "loadingDate",
        label: "Дата погрузки",
        type: "date",
        placeholder: "",
        required: true,
        group: "dates",
      },
      {
        id: "deliveryDeadline",
        label: "Срок доставки",
        type: "select",
        placeholder: "",
        required: true,
        group: "dates",
        options: [
          { value: "3", label: "3 рабочих дня с момента погрузки" },
          { value: "5", label: "5 рабочих дней с момента погрузки" },
          { value: "10", label: "10 рабочих дней с момента погрузки" },
        ],
      },
    ],
  },
  {
    id: "storage",
    name: "Договор хранения",
    shortName: "Хранение",
    description:
      "Принятие хранителем на ответственное хранение имущества поклажедателя с обязательством возврата в сохранности.",
    icon: "warehouse",
    category: "Услуги",
    estimatedTime: "3 мин",
    fields: [
      {
        id: "depositor",
        label: "Поклажедатель (название / ФИО)",
        type: "text",
        placeholder: "ООО «Поклажедатель»",
        required: true,
        group: "parties",
      },
      {
        id: "depositorInn",
        label: "ИНН поклажедателя",
        type: "text",
        placeholder: "7712345678",
        required: true,
        group: "parties",
      },
      {
        id: "keeper",
        label: "Хранитель (название)",
        type: "text",
        placeholder: "ООО «Склад»",
        required: true,
        group: "parties",
      },
      {
        id: "keeperInn",
        label: "ИНН хранителя",
        type: "text",
        placeholder: "7712345679",
        required: true,
        group: "parties",
      },
      {
        id: "items",
        label: "Описание имущества",
        type: "textarea",
        placeholder:
          "Партия офисной техники в упаковке производителя: 30 ноутбуков Dell Latitude, общая стоимость 3 600 000 руб.",
        required: true,
        group: "conditions",
      },
      {
        id: "storageAddress",
        label: "Адрес склада хранения",
        type: "text",
        placeholder: "Московская обл., г. Подольск, ул. Складская, д. 10",
        required: true,
        group: "conditions",
      },
      {
        id: "valuation",
        label: "Оценочная стоимость имущества (₽)",
        type: "number",
        placeholder: "3600000",
        required: true,
        group: "payment",
      },
      {
        id: "feePerMonth",
        label: "Стоимость хранения в месяц (₽)",
        type: "number",
        placeholder: "30000",
        required: true,
        group: "payment",
      },
      {
        id: "termMonths",
        label: "Срок хранения",
        type: "select",
        placeholder: "",
        required: true,
        group: "dates",
        options: [
          { value: "1", label: "1 месяц" },
          { value: "3", label: "3 месяца" },
          { value: "6", label: "6 месяцев" },
          { value: "12", label: "12 месяцев" },
          { value: "indefinite", label: "До востребования" },
        ],
      },
      {
        id: "insurance",
        label: "Страхование",
        type: "select",
        placeholder: "",
        required: false,
        group: "additional",
        options: [
          { value: "no", label: "Без страхования (риск на поклажедателе)" },
          { value: "keeper", label: "Хранитель страхует за свой счёт" },
          { value: "depositor", label: "Поклажедатель страхует за свой счёт" },
        ],
      },
    ],
  },
  {
    id: "termination-agreement",
    name: "Соглашение о расторжении договора",
    shortName: "Расторжение",
    description:
      "Прекращение действующего договора по соглашению сторон с урегулированием взаиморасчётов.",
    icon: "scissors",
    category: "Документооборот",
    estimatedTime: "2 мин",
    fields: [
      {
        id: "originalContractType",
        label: "Тип расторгаемого договора",
        type: "text",
        placeholder: "Договор аренды нежилого помещения",
        required: true,
        group: "parties",
      },
      {
        id: "originalContractNumber",
        label: "Номер расторгаемого договора",
        type: "text",
        placeholder: "3-А/2025",
        required: true,
        group: "parties",
      },
      {
        id: "originalContractDate",
        label: "Дата расторгаемого договора",
        type: "date",
        placeholder: "",
        required: true,
        group: "parties",
      },
      {
        id: "party1",
        label: "Первая сторона (название / ФИО)",
        type: "text",
        placeholder: "ООО «Арендодатель»",
        required: true,
        group: "parties",
      },
      {
        id: "party1Inn",
        label: "ИНН первой стороны",
        type: "text",
        placeholder: "7712345678",
        required: true,
        group: "parties",
      },
      {
        id: "party1Role",
        label: "Роль первой стороны",
        type: "text",
        placeholder: "Арендодатель",
        required: true,
        group: "parties",
      },
      {
        id: "party2",
        label: "Вторая сторона (название / ФИО)",
        type: "text",
        placeholder: "ООО «Арендатор»",
        required: true,
        group: "parties",
      },
      {
        id: "party2Inn",
        label: "ИНН второй стороны",
        type: "text",
        placeholder: "7712345678",
        required: true,
        group: "parties",
      },
      {
        id: "party2Role",
        label: "Роль второй стороны",
        type: "text",
        placeholder: "Арендатор",
        required: true,
        group: "parties",
      },
      {
        id: "terminationDate",
        label: "Дата прекращения договора",
        type: "date",
        placeholder: "",
        required: true,
        group: "dates",
      },
      {
        id: "settlement",
        label: "Состояние взаиморасчётов",
        type: "select",
        placeholder: "",
        required: true,
        group: "payment",
        options: [
          { value: "settled", label: "Стороны рассчитались полностью, претензий не имеют" },
          { value: "refund", label: "Первая сторона возвращает оплату второй стороне" },
          { value: "owed", label: "У сторон остаются взаимные обязательства (в Приложении)" },
        ],
      },
      {
        id: "refundAmount",
        label: "Сумма возврата, если применимо (₽)",
        type: "number",
        placeholder: "50000",
        required: false,
        group: "payment",
      },
      {
        id: "refundDeadline",
        label: "Срок возврата (рабочих дней)",
        type: "select",
        placeholder: "",
        required: false,
        group: "payment",
        options: [
          { value: "5", label: "5 рабочих дней" },
          { value: "10", label: "10 рабочих дней" },
          { value: "30", label: "30 календарных дней" },
        ],
      },
    ],
  },
];

export function getTemplate(id: string): DocumentTemplate | undefined {
  return templates.find((t) => t.id === id);
}
